# Generated by Django 4.1.2 on 2022-10-27 01:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('LW', 'Lightweight'), ('MW', 'Middleweight'), ('CW', 'Cruiserweight'), ('HW', 'Heavyweight')], max_length=15)),
                ('weight_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'IDLE'), (2, 'LOADING'), (3, 'LOADED'), (4, 'DELIVERING'), (5, 'DELIVERED'), (6, 'RETURNING')])),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Invalid Field', regex='^[a-zA-Z0-9\\-\\_]+$')])),
                ('weight', models.IntegerField()),
                ('code', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Invalid Field', regex='^[a-zA-Z0-9\\-]+$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='medication/%Y%m%d')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDrone',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('LW', 'Lightweight'), ('MW', 'Middleweight'), ('CW', 'Cruiserweight'), ('HW', 'Heavyweight')], max_length=15)),
                ('weight_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'IDLE'), (2, 'LOADING'), (3, 'LOADED'), (4, 'DELIVERING'), (5, 'DELIVERED'), (6, 'RETURNING')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Drone',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
