# Generated by Django 4.1.2 on 2022-10-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_medication_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
