# Generated by Django 4.1.2 on 2022-10-27 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_medication_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Invalid Field', regex='^[A-Z0-9\\_]+$')]),
        ),
    ]
